/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuctionDetailsRouteImport } from './routes/_authenticated/auction-details'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedAuctionMyAuctionsRouteImport } from './routes/_authenticated/_auction/my-auctions'
import { Route as AuthenticatedAuctionLiveAuctionsRouteImport } from './routes/_authenticated/_auction/live-auctions'
import { Route as AuthenticatedAuctionHowItWorksRouteImport } from './routes/_authenticated/_auction/how-it-works'
import { Route as AuthenticatedAuctionCreateAuctionRouteImport } from './routes/_authenticated/_auction/create-auction'
import { Route as AuthenticatedAuctionContactUsRouteImport } from './routes/_authenticated/_auction/contact-us'
import { Route as AuthenticatedAuctionAuctionAuctionIdRouteImport } from './routes/_authenticated/_auction/auction/$auctionId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuctionDetailsRoute =
  AuthenticatedAuctionDetailsRouteImport.update({
    id: '/auction-details',
    path: '/auction-details',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAuctionMyAuctionsRoute =
  AuthenticatedAuctionMyAuctionsRouteImport.update({
    id: '/_auction/my-auctions',
    path: '/my-auctions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuctionLiveAuctionsRoute =
  AuthenticatedAuctionLiveAuctionsRouteImport.update({
    id: '/_auction/live-auctions',
    path: '/live-auctions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuctionHowItWorksRoute =
  AuthenticatedAuctionHowItWorksRouteImport.update({
    id: '/_auction/how-it-works',
    path: '/how-it-works',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuctionCreateAuctionRoute =
  AuthenticatedAuctionCreateAuctionRouteImport.update({
    id: '/_auction/create-auction',
    path: '/create-auction',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuctionContactUsRoute =
  AuthenticatedAuctionContactUsRouteImport.update({
    id: '/_auction/contact-us',
    path: '/contact-us',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuctionAuctionAuctionIdRoute =
  AuthenticatedAuctionAuctionAuctionIdRouteImport.update({
    id: '/_auction/auction/$auctionId',
    path: '/auction/$auctionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/auction-details': typeof AuthenticatedAuctionDetailsRoute
  '/contact-us': typeof AuthenticatedAuctionContactUsRoute
  '/create-auction': typeof AuthenticatedAuctionCreateAuctionRoute
  '/how-it-works': typeof AuthenticatedAuctionHowItWorksRoute
  '/live-auctions': typeof AuthenticatedAuctionLiveAuctionsRoute
  '/my-auctions': typeof AuthenticatedAuctionMyAuctionsRoute
  '/auction/$auctionId': typeof AuthenticatedAuctionAuctionAuctionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/auction-details': typeof AuthenticatedAuctionDetailsRoute
  '/contact-us': typeof AuthenticatedAuctionContactUsRoute
  '/create-auction': typeof AuthenticatedAuctionCreateAuctionRoute
  '/how-it-works': typeof AuthenticatedAuctionHowItWorksRoute
  '/live-auctions': typeof AuthenticatedAuctionLiveAuctionsRoute
  '/my-auctions': typeof AuthenticatedAuctionMyAuctionsRoute
  '/auction/$auctionId': typeof AuthenticatedAuctionAuctionAuctionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/auction-details': typeof AuthenticatedAuctionDetailsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_auction/contact-us': typeof AuthenticatedAuctionContactUsRoute
  '/_authenticated/_auction/create-auction': typeof AuthenticatedAuctionCreateAuctionRoute
  '/_authenticated/_auction/how-it-works': typeof AuthenticatedAuctionHowItWorksRoute
  '/_authenticated/_auction/live-auctions': typeof AuthenticatedAuctionLiveAuctionsRoute
  '/_authenticated/_auction/my-auctions': typeof AuthenticatedAuctionMyAuctionsRoute
  '/_authenticated/_auction/auction/$auctionId': typeof AuthenticatedAuctionAuctionAuctionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/auction-details'
    | '/contact-us'
    | '/create-auction'
    | '/how-it-works'
    | '/live-auctions'
    | '/my-auctions'
    | '/auction/$auctionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/auction-details'
    | '/contact-us'
    | '/create-auction'
    | '/how-it-works'
    | '/live-auctions'
    | '/my-auctions'
    | '/auction/$auctionId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/auction-details'
    | '/_authenticated/'
    | '/_authenticated/_auction/contact-us'
    | '/_authenticated/_auction/create-auction'
    | '/_authenticated/_auction/how-it-works'
    | '/_authenticated/_auction/live-auctions'
    | '/_authenticated/_auction/my-auctions'
    | '/_authenticated/_auction/auction/$auctionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auction-details': {
      id: '/_authenticated/auction-details'
      path: '/auction-details'
      fullPath: '/auction-details'
      preLoaderRoute: typeof AuthenticatedAuctionDetailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/_auction/my-auctions': {
      id: '/_authenticated/_auction/my-auctions'
      path: '/my-auctions'
      fullPath: '/my-auctions'
      preLoaderRoute: typeof AuthenticatedAuctionMyAuctionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_auction/live-auctions': {
      id: '/_authenticated/_auction/live-auctions'
      path: '/live-auctions'
      fullPath: '/live-auctions'
      preLoaderRoute: typeof AuthenticatedAuctionLiveAuctionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_auction/how-it-works': {
      id: '/_authenticated/_auction/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AuthenticatedAuctionHowItWorksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_auction/create-auction': {
      id: '/_authenticated/_auction/create-auction'
      path: '/create-auction'
      fullPath: '/create-auction'
      preLoaderRoute: typeof AuthenticatedAuctionCreateAuctionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_auction/contact-us': {
      id: '/_authenticated/_auction/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof AuthenticatedAuctionContactUsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_auction/auction/$auctionId': {
      id: '/_authenticated/_auction/auction/$auctionId'
      path: '/auction/$auctionId'
      fullPath: '/auction/$auctionId'
      preLoaderRoute: typeof AuthenticatedAuctionAuctionAuctionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuctionDetailsRoute: typeof AuthenticatedAuctionDetailsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuctionContactUsRoute: typeof AuthenticatedAuctionContactUsRoute
  AuthenticatedAuctionCreateAuctionRoute: typeof AuthenticatedAuctionCreateAuctionRoute
  AuthenticatedAuctionHowItWorksRoute: typeof AuthenticatedAuctionHowItWorksRoute
  AuthenticatedAuctionLiveAuctionsRoute: typeof AuthenticatedAuctionLiveAuctionsRoute
  AuthenticatedAuctionMyAuctionsRoute: typeof AuthenticatedAuctionMyAuctionsRoute
  AuthenticatedAuctionAuctionAuctionIdRoute: typeof AuthenticatedAuctionAuctionAuctionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuctionDetailsRoute: AuthenticatedAuctionDetailsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuctionContactUsRoute: AuthenticatedAuctionContactUsRoute,
  AuthenticatedAuctionCreateAuctionRoute:
    AuthenticatedAuctionCreateAuctionRoute,
  AuthenticatedAuctionHowItWorksRoute: AuthenticatedAuctionHowItWorksRoute,
  AuthenticatedAuctionLiveAuctionsRoute: AuthenticatedAuctionLiveAuctionsRoute,
  AuthenticatedAuctionMyAuctionsRoute: AuthenticatedAuctionMyAuctionsRoute,
  AuthenticatedAuctionAuctionAuctionIdRoute:
    AuthenticatedAuctionAuctionAuctionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
